language: perl
perl:
  - "5.28"
  # - "5.26"
  # - "5.24"
  # - "5.22"
  # - "5.20"
  # - "5.18"

services:
  - docker
  
env:
  - |
    NEO4J_VER=3.5 REST_NEO4P_AGENT_MODULE=Mojo::UserAgent
  - |
    NEO4J_VER=4.2 REST_NEO4P_AGENT_MODULE=Neo4j::Driver
  - |
    NEO4J_VER=3.5 REST_NEO4P_AGENT_MODULE=Neo4j::Driver

before_install:
  # canned server
  - docker pull $DOCKERH/testneo/testneo:$NEO4J_VER
  # perl pkgs
  - cpanm Test::Pod Test::CPAN::Changes

install:
  - export REST_NEO4P_BUILD_NONINTERACTIVE=1
  - export REST_NEO4P_TEST_SERVER=http://localhost:7474
  - export REST_NEO4P_TEST_USER=''
  - export REST_NEO4P_TEST_PASS=''
  - perl Build.PL
  - yes | ./Build installdeps --cpan_client 'cpanm -n'

script:
  - docker run -d -p 127.0.0.1:7474:7474 -p 127.0.0.1:7473:7473 -p 127.0.0.1:7687:7687 --env NEO4J_AUTH=none --name testneo $DOCKERH/testneo/testneo:$NEO4J_VER ;
  - sleep 10
  - ./Build test
  - docker kill testneo
  - docker rm testneo

  


  
