
language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  # - "5.20"
  # - "5.18"

env:
  - NEO4J_VER=1:3.3.9
  - NEO4J_VER=1:3.5.14
  - NEO4J_VER=1:3.4.17




before_install:
  # neo4j pkgs
  - curl https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb http://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  # perl pkgs
  - cpanm Test::Pod Test::CPAN::Changes

install:
  - yes | sudo apt-get install daemon adduser psmisc lsb-base openjdk-8-jdk
  - ls -a /usr/lib/jvm 
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - java -version
  - echo N | sudo apt-get -y install neo4j=$NEO4J_VER
  - sudo neo4j start
  - sleep 20

  # need to change pass on first access
  - curl -u neo4j:neo4j -d '{"password":"j4oen"}' -X POST -H 'Accept:application/json' -H'Content-Type:application/json' http://localhost:7474/user/neo4j/password
  
#before_script:
#  - sudo neo4j start

script:
  - export REST_NEO4P_TEST_SERVER=http://localhost:7474
  - export REST_NEO4P_TEST_USER=neo4j
  - export REST_NEO4P_TEST_PASS=j4oen
  - perl Build.PL
  - yes | ./Build installdeps --cpan_client 'cpanm -n'
  - for REST_NEO4P_AGENT_MODULE in LWP::UserAgent Mojo::UserAgent HTTP::Thin ; do ./Build test ; done
  


  
