name: test-rest-neo4p
on:
  push:
    branches:
      - ci-actions
  pull_request:
    branches:
      - master
jobs:
  do:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      NEO4J_VER: 3.5
      REST_NEO4P_AGENT_MODULE: "Neo4j::Driver"
    steps:
      - uses: actions/checkout@v2
      - name: install perl things
        run: |
          sudo apt-get install -y cpanminus
          cpanm --sudo Module::Build
      - name: start_neo 
        env: 
          DOCKERH: ${{ secrets.DOCKERH }}
        run: |
          docker pull $DOCKERH/testneo/testneo:$NEO4J_VER 
          docker run -d -p 127.0.0.1:7474:7474 -p 127.0.0.1:7473:7473 -p 127.0.0.1:7687:7687 --env NEO4J_AUTH=none --name testneo $DOCKERH/testneo/testneo:$NEO4J_VER 
          sleep 10 
      - name: build
        env:
          REST_NEO4P_BUILD_NONINTERACTIVE: 1
          REST_NEO4P_TEST_SERVER: http://localhost:7474
          REST_NEO4P_TEST_USER: ''
          REST_NEO4P_TEST_PASS: ''
        run: |
          perl ./Build.PL
          echo y$'\n'y | ./Build installdeps --cpan_client 'cpanm --sudo -n' 
          ./Build
      - name: test
        run: |
          ./Build test
          

          
    
